name: Release
on: 
  release:
    types: [published]

jobs:
  zip-files:
    name: Zip
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: vimtor/action-zip@v1.1
        with:
          files: 'BUILD/Components/4DPop%20XLIFF%20Pro.4dbase/Contents/'
          dest: 4DPop-XLIFF-Pro.zip
  publish:
    name: Publish
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    permissions:
      contents: write # for asset upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload
        run: |
          gh release upload ${{github.event.release.tag_name}} BUILD/4DPop-XLIFF-Pro.zip
